# This container returns only a redirect for satayo.guide to satayo entry page
# docker build -t docker-si.wuerth-phoenix.com/satayo-userguide-unprivileged:latest -f Dockerfile.satayo .
# docker run -it --rm -p8080:8080 docker-si.wuerth-phoenix.com/satayo-userguide-unprivileged:latest
FROM docker.io/nginxinc/nginx-unprivileged:alpine

COPY satayo/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080
