# This file showld be overwritten with a config map to adapt nginx configuration
# to run properly on openshift.
#
# For example on openshift is required to add inside the server
# port_in_redirect off;
# to avoid to be redirect on port 8080, while locally this can be useful to use a
# custom port for testing.
