listen       8080;
listen  [::]:8080;
server_name  _;

location = /versions.json {

    # The below headers are necessary for enabling the CORS requests
    add_header Access-Control-Allow-Origin * always;
    add_header Access-Control-Allow-Headers "Content-Type" always;
    add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
    add_header Allow "GET, OPTIONS" always;

    if ($request_method = OPTIONS ) {
        return 200;
    }

    root /usr/share/nginx/html/;
}

location / {
    root   /usr/share/nginx/html/;
    # redirect neteye.guide to neteye.guide/current
    rewrite "^/$" "/current/" permanent;
}

location ~* /current(.*) {
    return 302 /@@CURRENT_VERSION@@$1;
}

location ~* /next(.*) {
    return 302 /@@NEXT_VERSION@@$1;
}

location ~* /alpha(.*) {
    return 302 /@@ALPHA_VERSION@@$1;
}

error_page 404 @error404;

location @error404 {
    root /usr/share/nginx/html/;

    if ($request_uri ~ "^/([0-9]\.[0-9]+|current|next|alpha)/") {
        set $version $1;
    }

    if (-f $document_root/$version/404.html) {
        return 302 /$version/404.html;
    }

    return 302 /@@CURRENT_VERSION@@/archived.html;
}
