#!/usr/bin/env python3
# NetEye User Guide documentation build configuration file, created by
# sphinx-quickstart on Wed Sep 30 08:08:27 2020.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import json
import os
import re
import time
import warnings
from copy import deepcopy
from pathlib import Path

from docutils import nodes
from sphinx import addnodes
from sphinx.environment.adapters.toctree import TocTree

current_year = time.strftime("%Y")

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
# sys.path.insert(0, os.path.abspath('.'))

# -- General configuration -----------------------------------------------------

## define variables
# The UG_NETEYE_VERSION environment variable must be set by the caller of the sphinx build, in the format "4.33"
neteye_version = os.getenv("UG_NETEYE_VERSION")
split_ne_version = neteye_version.split(".", 1)
neteye_major = split_ne_version[0]
neteye_minor = split_ne_version[1]
neteye_previous_version = f"{neteye_major}.{int(neteye_minor) - 1}"
neteye_following_version = f"{neteye_major}.{int(neteye_minor) + 1}"

# Retrieve feature variable
feature = os.getenv("FEATURE")
# If feature is "prod", we set it to None, so that the master_doc is "index" and not "index-prod"
if feature == "prod":
    feature = None

# Check if we are running in development mode
if os.getenv("DEVELOPMENT_MODE"):
    development_mode = os.getenv("DEVELOPMENT_MODE").strip().lower() in (
        "true",
        "1",
        "yes",
        "y",
        "on",
    )
else:
    development_mode = False

source_directory = "source"


## build test URLs for telegraf packages. they use variables version
## and release defined above and are exported through rst_prolog
## below.
##
## They should not be used in code-blocks:: but in parsed-literal::
tg_deb = (
    "https://repo.wuerth-phoenix.com/debian/x86_64/neteye-"
    + neteye_version
    + "-telegraf/"
)
tg_win = (
    "https://repo.wuerth-phoenix.com/windows/x86_64/neteye-"
    + neteye_version
    + "-telegraf/"
)
tg_rh = (
    "https://repo.wuerth-phoenix.com/centos/x86_64/neteye-"
    + neteye_version
    + "-telegraf/"
)
tg_linux = (
    "https://repo.wuerth-phoenix.com/linux-generic/x86_64/neteye-"
    + neteye_version
    + "-telegraf/"
)

rst_prolog = f"""
.. |chevron| image:: /icons/chevron.ico
   :width: 12px
.. |reload| image:: /icons/reload.ico
   :width: 12px
.. |edit| image:: /icons/edit.ico
   :width: 12px
.. |trashbin| image:: /icons/trash-bin.ico
   :width: 12px
.. |uparrow| image:: /icons/up-arrow.ico
   :width: 8px
.. |downarrow| image:: /icons/down-arrow.ico
   :width: 8px
.. |gear| image:: /icons/gear.ico
   :width: 8px
.. role:: phone
.. |witit| replace:: Würth IT Italy
.. |ne| replace:: NetEye
.. |neb| replace:: **NetEye**
.. |nei| replace:: `NetEye`
.. |tg_deb| replace:: {tg_deb}
.. |tg_win| replace:: {tg_win}
.. |tg_rh| replace:: {tg_rh}
.. |tg_linux| replace:: {tg_linux}
.. |neteye_version| replace:: {neteye_version}
.. |neteye_version_bold| replace:: **{neteye_version}**
.. |neteye_previous_version| replace:: {neteye_previous_version}
.. |neteye_previous_version_bold| replace:: **{neteye_previous_version}**
.. |neteye_following_version| replace:: {neteye_following_version}
.. |neteye_following_version_bold| replace:: **{neteye_following_version}**
.. |satellite_config_file| replace:: :file:`/root/satellite-setup/config/{neteye_version}/satellite-config.tar.gz`
.. |support| replace:: support portal
.. _support: https://servicedesk.wuerth-it.it/
.. |current_year| replace:: {current_year}
"""

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
# - jquery added because it has been removed from spring 6 while it was present in sphinx 5.3, see:
#   https://www.sphinx-doc.org/en/master/changes.html#id41
extensions = [
    "sphinx.ext.todo",
    "sphinx.ext.ifconfig",
    "sphinx_copybutton",
    "sphinxcontrib.jquery",
]

# -- List of options required by the extensions to work properly ---------------

numfig = True

todo_include_todos = False
todo_link_only = False

# Link checker
linkcheck_request_headers = {
    "*": {
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/145.0.7632.110 Safari/537.36"
        ),
    },
}
linkcheck_anchors = True
linkcheck_ignore = [
    "https://docs.fortinet.com/document/fortiauthenticator/6.6.2/administration-guide/154496/scopes",  # Sometimes il fails to resolve
    "https://docs.fortinet.com/document/fortiauthenticator/6.6.2/administration-guide/796040/relying-party#Claims",  # Sometimes il fails to resolve
    "https://elasticsearch.neteyelocal:9200",  # Local Elasticsearch instance
    "https://indicatorblacklist.satayo.cloud",  # Authentication required
    "https://pulpproject.org",  # Extremely slow to respond
    "https://repo.wuerth-phoenix.com/",  # VPN required
    "https://servicedesk.wuerth-it.it",  # Temporary broken certificates
    "https://www.dell.com/support/manuals/it-it/poweredge-fx2/idrac8_2.30.30.30_ug",  # It returns 403
    "https://www.freedesktop.org/software/systemd/man/latest/systemd.time.html#Calendar%20Events",  # Bot checker
    "https://www.freedesktop.org/software/systemd/man/latest/systemd.timer.html",  # Bot checker
    "https://www.postfix.org/documentation.html",  # Extremely slow to respond
]
linkcheck_anchors_ignore_for_url = [
    "https://www.elastic.co/support/matrix",  # Anchor not found by linkcheck
]
linkcheck_rate_limit_timeout = 10
linkcheck_retries = 2
linkcheck_timeout = 10

manpages_url = "https://manpages.debian.org/{path}"

## -- Options for Copybutton extension -------------------------------------------

copybutton_prompt_is_regexp = True

# RegExp to match prompts used in code snippet

# IMPORTANT: we can not use round parenthesis `(` `)` in the regexp
# due to a possible bug in (or wrong implementation of)
# sphinx_copybutton extension. See discussion at
# https://github.com/executablebooks/sphinx-copybutton/issues/96.

copybutton_prompt_text = (
    r"neteye#\s|sat#\s|cluster#\s|cluster-node.+#\s|elastic-only#\s|voting-only#\s|#\s"
)

#####

# The suffix of source filenames.
source_suffix = ".rst"

# The encoding of source files.
# source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = "index" if not feature else f"index-{feature}"

# General information about the project.
project = "NetEye User Guide"
copyright = "&copy; %s, Würth IT Italy s.r.l." % (current_year)

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
# version = '4.20'
# The full version, including alpha/beta/rc tags.
# release = '4.20'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
# language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
# today_fmt = '%B %d, %Y'


html_theme = "neteye-carbon"
templates_path = ["./theme/neteye-carbon/templates"]

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.

# Exclude all index files except the master_doc one
exclude_patterns = ["**/*.inc.rst"]
index_files_to_exclude = list(Path(source_directory).glob("index*.rst"))
exclude_patterns.extend(
    [f.name for f in index_files_to_exclude if f.name != f"{master_doc}.rst"],
)

# Avoid warnings for non-case sensitive glossary entries
suppress_warnings = ["ref.term"]

# The reST default role (used for this markup: `text`) to use for all documents.
# default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
# add_function_parentheses = True
# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
# add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
# show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "trac"

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []


# -- Options for HTML output ---------------------------------------------------

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
html_theme_path = ["./theme"]

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
html_title = "%s" % (project)

# A shorter title for the navigation bar.  Default is the same as html_title.
# html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = "./source/img/neteye-logo.svg"

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = "./source/img/favicon.png"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["./_static"]

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
# html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
# html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
# html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
html_additional_pages = {
    "index": "index.html",
    "404": "404.html",
    "archived": "archived.html",
}

# If false, no module index is generated.
# html_domain_indices = True

# If false, no index is generated.
# html_use_index = True

# If true, the index is split into individual pages for each letter.
# html_split_index = False

# If true, links to the reST sources are added to the pages.
# html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
# html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
# html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
# html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = "NetEyeUserGuidedoc"


# -- Options for LaTeX output --------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #'preamble': '',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual]).
latex_documents = [
    (
        "index",
        "NetEyeUserGuide.tex",
        "NetEye User Guide Documentation",
        "NetEye Team",
        "manual",
    ),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
# latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
# latex_use_parts = False

# If true, show page references after internal links.
# latex_show_pagerefs = False

# If true, show URL addresses after external links.
# latex_show_urls = False

# Documents to append as an appendix to all manuals.
# latex_appendices = []

# If false, no module index is generated.
# latex_domain_indices = True


# -- Options for manual page output --------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (
        "index",
        "neteyeuserguide",
        "NetEye User Guide Documentation",
        ["NetEye Team"],
        1,
    ),
]

# If true, show URL addresses after external links.
# man_show_urls = False


# -- Options for Texinfo output ------------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        "index",
        "NetEyeUserGuide",
        "NetEye User Guide Documentation",
        "NetEye Team",
        "NetEyeUserGuide",
        "One line description of project.",
        "Miscellaneous",
    ),
]

# Documents to append as an appendix to all manuals.
# texinfo_appendices = []

# If false, no module index is generated.
# texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
# texinfo_show_urls = 'footnote'


# -- Options for Epub output ---------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = "NetEye User Guide"
epub_author = "NetEye Team"
epub_publisher = "NetEye Team"
epub_copyright = "2020, NetEye Team"

# The language of the text. It defaults to the language option
# or en if the language is not set.
# epub_language = ''

# The scheme of the identifier. Typical schemes are ISBN or URL.
# epub_scheme = ''

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
# epub_identifier = ''

# A unique identification for the text.
# epub_uid = ''

# A tuple containing the cover image and cover page html template filenames.
# epub_cover = ()

# HTML files that should be inserted before the pages created by sphinx.
# The format is a list of tuples containing the path and title.
# epub_pre_files = []

# HTML files that should be inserted after the pages created by sphinx.
# The format is a list of tuples containing the path and title.
# epub_post_files = []

# A list of files that should not be packed into the epub file.
# epub_exclude_files = []

# The depth of the table of contents in toc.ncx.
# epub_tocdepth = 3

# Allow duplicate toc entries.
# epub_tocdup = True


def toctree_to_json(node, pagename):
    """Recursively convert a Sphinx toctree node into a structured JSON format."""

    # Handle node traversal with level tracking
    def process_node(node, pagename, level=0, parent_title=None):
        # Handle list items
        if isinstance(node, nodes.list_item):
            result = {}
            title = None

            # Process each child of the list item
            for child in node.children:
                # First paragraph/compact_paragraph is the title+link
                if isinstance(child, nodes.paragraph) or isinstance(
                    child,
                    addnodes.compact_paragraph,
                ):
                    for ref_child in child.children:
                        if isinstance(ref_child, nodes.reference):
                            title = ref_child.astext().strip()
                            href = ref_child.get("refuri", "#")
                            result["title"] = title
                            result["href"] = href
                            break

                # Nested bullet list becomes children
                elif isinstance(child, nodes.bullet_list):
                    children = process_node(child, pagename, level + 1, title)
                    if children and isinstance(children, list) and len(children) > 0:
                        result["children"] = children

            return result

        # Handle bullet lists
        if isinstance(node, nodes.bullet_list):
            items = []
            for child in node.children:
                item = process_node(child, pagename, level, parent_title)
                if item:
                    items.append(item)
            return items

        # Handle compact_paragraph - this is where we need to fix the handling
        if isinstance(node, addnodes.compact_paragraph):
            # Process all child elements in order
            bullet_lists = []
            reference_item = None

            # First, collect all bullet lists and check for a reference
            for child in node.children:
                if isinstance(child, nodes.bullet_list):
                    bullet_list_items = process_node(
                        child,
                        pagename,
                        level,
                        parent_title,
                    )
                    if bullet_list_items:
                        bullet_lists.append(bullet_list_items)
                elif isinstance(child, nodes.reference) and not reference_item:
                    reference_item = {
                        "title": child.astext().strip(),
                        "href": child.get("refuri", "#"),
                    }

            # If we have a reference item, return it with children if available
            if reference_item:
                # If we have bullet lists, they become children of the reference item
                if bullet_lists:
                    # Flatten all bullet lists into a single children array
                    all_children = []
                    for bl in bullet_lists:
                        if isinstance(bl, list):
                            all_children.extend(bl)
                        else:
                            all_children.append(bl)

                    if all_children:
                        reference_item["children"] = all_children

                return reference_item

            # If we have bullet lists but no reference, combine them
            if bullet_lists:
                if len(bullet_lists) == 1:
                    return bullet_lists
                # Merge multiple bullet lists into a single list
                all_items = []
                for bl in bullet_lists:
                    if isinstance(bl, list):
                        all_items.extend(bl)
                    else:
                        all_items.append(bl)
                return all_items

            # As a fallback, just return the text content
            return {"title": node.astext().strip()}

        # Handle reference nodes (links)
        if isinstance(node, nodes.reference):
            return {
                "title": node.astext().strip(),
                "href": node.get("refuri", "#"),
            }

        # Default case for any other node with children
        if hasattr(node, "children") and node.children:
            # Process all children to find meaningful content
            for child in node.children:
                result = process_node(child, pagename, level, parent_title)
                if result:
                    return result

            return None

        return None

    # Start processing from the top level
    return process_node(node, pagename)


# this function recursively searches for the json item containing an empty href and marks its entire parent genealogy with "status: active".
def build_active_statuses(json, max_depth=10, depth=0):
    if (
        depth > max_depth
    ):  # This check is necessary to prevent some href references from causing an infinite loop
        warnings.warn(
            "A 'build_active_statuses' recursion has reached its max depth. This might cause undefined behavior on the frontend.",
        )
        return False

    # if we found the 'active' submenu (which is an empty href, due to sphinx), we add the 'status:active' mark and return True,
    # so that the 'parent' recursion knows that one of its children is 'active' and thus has to mark the parent as also active.
    if json["href"] == "":
        json["status"] = "active"
        return True

    if "children" in json:
        for child in json["children"]:
            # For each children, recursively check if it leads to an active submenu item. If so, mark the current element as active.
            if build_active_statuses(child, depth=depth + 1):
                json["status"] = "active"
                return True
    return False


# This function removes elements from a json menu ('data') referring to the same page (i.e. containing a #), as they are
# not included in the the main menu and as such would require the frontend code to filter out these elements. By doing it here,
# we achieve more efficiency.
def remove_same_page_href(data, maxdepth=10, depth=0):
    if depth > maxdepth:  # Prevent infinite loops
        warnings.warn(
            "A 'remove_same_page_href' recursion has reached its max depth. This might cause undefined behavior on the frontend.",
        )
        return

    if isinstance(data, dict):
        # Remove children with hrefs that contain "#"
        if "children" in data:
            data["children"] = [
                child
                for child in data["children"]
                if not (
                    isinstance(child, dict) and "href" in child and "#" in child["href"]
                )
            ]
            # Recurse on filtered children
            for child in data["children"]:
                remove_same_page_href(child, maxdepth=maxdepth, depth=depth + 1)

    elif isinstance(data, list):
        for item in data:
            remove_same_page_href(item, maxdepth=maxdepth, depth=depth + 1)


def get_toc_data(app, pagename, templatename, context, doctree):
    """Get toc data and add it to the context for the current page."""
    env = app.builder.env
    builder = app.builder

    # Get the toctree for the current page
    toctree = TocTree(env).get_toctree_for(
        pagename,
        builder,
        collapse=False,
        maxdepth=4,
    )

    if toctree:
        full_menu = toctree_to_json(toctree, pagename)

        remove_same_page_href(full_menu)

        local_toc_data, parent_loc_data = None, None
        for menu in full_menu:
            build_active_statuses(menu)

            for module in menu["children"]:
                if "status" in module:
                    if module["status"] == "active":
                        local_toc_data = module
                        parent_loc_data = menu

        context["toc_data"] = full_menu
        context["local_toc_data"] = local_toc_data
        context["parent_toc_data"] = parent_loc_data

        conf_dir = Path(__file__).parent.resolve()
        json_path = (
            conf_dir
            / "theme"
            / "neteye-carbon"
            / "static"
            / "conf"
            / "sections-data.json"
        )
        with Path.open(json_path) as file:
            json_data = json.load(file)

        if "core-modules/" in pagename:
            pattern = r"core-modules/([^/]+)"
            current_module = re.search(pattern, pagename).group(1)
            modules = json_data["core-modules"].get(current_module)

            if modules:
                context["side_panel_icon"] = modules["icon"]
                context["current_module_name"] = modules["name"]

        elif "feature-modules/" in pagename:
            pattern = r"feature-modules/([^/]+)"
            current_module = re.search(pattern, pagename).group(1)
            modules = json_data["feature-modules"].get(current_module)

            if modules:
                context["side_panel_icon"] = modules["icon"]
                context["current_module_name"] = modules["name"]

        elif "satayo" in pagename:
            modules = json_data["feature-modules"].get("satayo")

            if modules:
                context["side_panel_icon"] = modules["icon"]
                context["current_module_name"] = modules["name"]
        elif "security-policy" in pagename:
            sec_policy = json_data["sections"].get("security-policy")

            if sec_policy:
                context["side_panel_icon"] = sec_policy["icon"]
        elif "neteye-cloud" in pagename:
            neteye_cloud = json_data["sections"].get("neteye-cloud")

            if neteye_cloud:
                context["side_panel_icon"] = neteye_cloud["icon"]
        else:
            parts = pagename.split("/")
            if len(parts) > 1 and parts[1]:
                current_section = parts[1]
            else:
                current_section = parts[0]
            section = json_data["sections"].get(current_section)

            if section:
                context["side_panel_icon"] = section["icon"]

        # If it's a "functional overview" page, then also build the "linked-modules" section
        # the "/" is important in order to skip the "functional-overview.html" page
        if "functional-overview/" in pagename:
            pattern = r"functional-overview/([^/]+?)(?:/|\.html|$)"
            current_page = re.search(pattern, pagename).group(1)
            linked_modules = (
                json_data["functional-overview"].get(current_page).get("linked-modules")
            )

            if linked_modules:
                # Array of modules, where we will store the json data of each module
                context_linked_modules = []
                for link in linked_modules:
                    # The format is e.g. "core-modules.director"
                    type, name = link.split(".", 1)

                    mod_j_data = deepcopy(json_data[type][name])

                    module_link = None
                    for element in context["toc_data"]:
                        if f"{type}.html" in element["href"]:
                            for child in element["children"]:
                                if f"{name}.html" in child["href"]:
                                    if child.get("children"):
                                        module_link = child["children"][0]["href"]
                                    else:
                                        module_link = child["href"]
                                    break

                    mod_j_data["built-sphinx-link"] = f"{module_link}"

                    context_linked_modules.append(mod_j_data)

                context["linked_modules"] = context_linked_modules

    else:
        context["toc_data"] = json.dumps(
            {"error": "No toctree found for this page"},
        )

    context["icons"] = json_data


def setup(app):
    app.connect("html-page-context", get_toc_data)
